# 'true' lets you create portals from ANY block type.
# Players will be teleported instantly when they enter a portal.
# 'false' lets you create portals from NETHER PORTAL BLOCKS ONLY.
# Players will have to wait a little bit before teleportation (simulating nether portal mechanics).
# This mode is very performance-friendly, you can use it on large survival servers
UseQuickPortals: true
# Should the plugin send annonymous stats about it's usage?
UseMetrics: true